/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.gui;

import controller.dao.EstudanteDao;
import javax.swing.JOptionPane;
import model.design.Estudante;
import view.model.TableModelEstudante;

/**
 *
 * @author gilberto
 */
public class EstudanteGui extends javax.swing.JFrame {
    //Criação e instância do objeto da classe Table Model
    TableModelEstudante modelo = new TableModelEstudante();
    //Criação do objeto da classe DAO
    EstudanteDao estudanteDao;

    /**
     * Creates new form EstudanteGui
     */
    public EstudanteGui() {
        initComponents();
        tblEstudante.setModel(modelo);
        this.lerTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEstudante = new javax.swing.JPanel();
        lblRm = new javax.swing.JLabel();
        txtRm = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudante = new javax.swing.JTable();
        btnGravar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Estudantes");

        lblRm.setText("RM:");

        lblNome.setText("Nome:");

        tblEstudante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEstudante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudanteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstudante);

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEstudanteLayout = new javax.swing.GroupLayout(pnlEstudante);
        pnlEstudante.setLayout(pnlEstudanteLayout);
        pnlEstudanteLayout.setHorizontalGroup(
            pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstudanteLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnGravar)
                .addGap(34, 34, 34)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(51, 51, 51)
                .addComponent(btnLimpar)
                .addGap(60, 60, 60))
            .addGroup(pnlEstudanteLayout.createSequentialGroup()
                .addGroup(pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstudanteLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblRm))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEstudanteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlEstudanteLayout.setVerticalGroup(
            pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstudanteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRm)
                    .addComponent(txtRm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnLimpar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lerTabela(){
        //Objeto DAO
         estudanteDao = new EstudanteDao();
         
         //Limpando a tabela
         modelo.clearTable();
        
        for(Estudante e: estudanteDao.read())
            modelo.addRow(e);
        
    }
    
    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        try{
            estudanteDao.create(new Estudante(
                    txtRm.getText(),
                    txtNome.getText())
            );
            /*
            modelo.addRow(new Estudante(
                    txtRm.getText(),
                    txtNome.getText())
            );
            */
            btnLimparActionPerformed(evt);
            this.lerTabela();
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtRm.setText(null);
        txtNome.setText(null);
        txtRm.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        int linha = tblEstudante.getSelectedRow();
        
        if(linha != -1){
            estudanteDao = new EstudanteDao();
            estudanteDao.update(new Estudante(
                    txtRm.getText(),
                    txtNome.getText()),
                    //Usa-se o RM da linha selecionada como parâmetro
                    String.valueOf(modelo.getValueAt(linha, 0))
            );
            
            /*
            modelo.setValueAt(txtRm.getText(), linha, 0);
            modelo.setValueAt(txtNome.getText(), linha, 1);
            */
        }
        this.btnLimparActionPerformed(evt);
        this.lerTabela();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblEstudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudanteMouseClicked
        // TODO add your handling code here:
        int linha = tblEstudante.getSelectedRow();
        
        if(linha != -1){
            txtRm.setText(String.valueOf(modelo.getValueAt(linha, 0)));
            txtNome.setText(String.valueOf(modelo.getValueAt(linha, 1)));
        }
        
    }//GEN-LAST:event_tblEstudanteMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tblEstudante.getSelectedRow();
        
        if(linha != -1){
            estudanteDao = new EstudanteDao();
            estudanteDao.delete(new Estudante(
                    txtRm.getText(),
                    txtNome.getText())
            );
            //modelo.removeRow(linha);
        }
        this.btnLimparActionPerformed(evt);
        this.lerTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudanteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudanteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudanteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudanteGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudanteGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRm;
    private javax.swing.JPanel pnlEstudante;
    private javax.swing.JTable tblEstudante;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRm;
    // End of variables declaration//GEN-END:variables
}
